### ISSUE TITLE
Missing Enhancement Crystal Name

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/Avaritia-Complement#3]
The item name for the enhancement crystal is missing. I only have Avaritia, AvaritiaTweaks, codechickencore and JEI as mods.
![2019-06-09_23 07 23](https://user-images.githubusercontent.com/50294702/59160694-72e4a900-8b0b-11e9-89fe-e25bcfa3a60f.png)

**Comment by Tfarcenim** [comment]
woops I broke the names when migrating them to new mappings, will fix asap

**Comment by Tfarcenim** [comment]
fixed in 1.2a
